type: base
build:
  auto_version: true
  architectures:
    - amd64
    - aarch64
  variants:
    - tag: "15-pkg"
      args:
        PKG_BRANCH: quarterly
    - tag: "15-pkg-latest"
      args:
        PKG_BRANCH: latest
    - tag: "15.1-pkg"
      args:
        FREEBSD_RELEASE: "15.1"
        PKG_BRANCH: quarterly
      aliases: ["latest"]
    - tag: "15.1-pkg-latest"
      args:
        FREEBSD_RELEASE: "15.1"
        PKG_BRANCH: latest

cit:
  mode: shell
  puid: false
